module.exports =   [
    {
        "id": 0,
        "imgUrl": "https://i.ibb.co/0GFzTP4/Rectangle-131.png",
        "productTitle": "Apple Watch Series , Aluminium Case, Starlight Sport",
        "productColor": "Silver",
        "productCategory": "Laptop",
        "accessories": "Yes",
        "available": "Yes",
        "productPrice": 299,
        "productStock": 4,
        "productRating": 5.0,
        "selected": false
    },
    {
        "id": 1,
        "imgUrl": "https://i.ibb.co/0GFzTP4/Rectangle-131.png",
        "productTitle": "Microsoft Surface Pro, Aluminium Case, Starlight Spor",
        "productColor": "Silver",
        "productCategory": "Laptop",
        "accessories": "Yes",
        "available": "Yes",
        "productPrice": 999,
        "productStock": 104,
        "productRating": 5.0,
        "selected": false
    },
    {
        "id": 2,
        "imgUrl": "https://i.ibb.co/0GFzTP4/Rectangle-131.png",
        "productTitle": "Magic Mouse 2, Aluminium Case, Starlight Spor",
        "productColor": "Silver",
        "productCategory": "Laptop",
        "accessories": "Yes",
        "available": "Yes",
        "productPrice": 2949,
        "productStock": 10,
        "productRating": 5.0,
        "selected": false
    },
    {
        "id": 3,
        "imgUrl": "https://i.ibb.co/0GFzTP4/Rectangle-131.png",
        "productTitle": "Bluetuth Watch, Aluminium Case, Starlight Spor",
        "productColor": "Silver",
        "productCategory": "Laptop",
        "accessories": "Yes",
        "available": "Yes",
        "productPrice": 499,
        "productStock": 12,
        "productRating": 5.0,
        "selected": false
    },
    {
        "id": 4,
        "imgUrl": "https://i.ibb.co/0GFzTP4/Rectangle-131.png",
        "productTitle": "Carbon Series , Aluminium Case, Starlight Sport",
        "productColor": "Silver",
        "productCategory": "Laptop",
        "accessories": "Yes",
        "available": "Yes",
        "productPrice": 399,
        "productStock":76,
        "productRating": 5.0,
        "selected": false
    },
    {
        "id": 5,
        "imgUrl": "https://i.ibb.co/0GFzTP4/Rectangle-131.png",
        "productTitle": "Desktop Surface Pro, Aluminium Case, Starlight Spor",
        "productColor": "Silver",
        "productCategory": "Laptop",
        "accessories": "Yes",
        "available": "Yes",
        "productPrice": 599,
        "productStock": 74,
        "productRating": 5.0,
        "selected": false
    },
    {
        "id": 6,
        "imgUrl": "https://i.ibb.co/0GFzTP4/Rectangle-131.png",
        "productTitle": "Elona Mouse 2, Aluminium Case, Starlight Spor",
        "productColor": "Silver",
        "productCategory": "Laptop",
        "accessories": "Yes",
        "available": "Yes",
        "productPrice": 199,
        "productStock": 5,
        "productRating": 5.0,
        "selected": false
    },
    {
        "id": 7,
        "imgUrl": "https://i.ibb.co/0GFzTP4/Rectangle-131.png",
        "productTitle": "Fireball Watch, Aluminium Case, Starlight Spor",
        "productColor": "Silver",
        "productCategory": "Laptop",
        "accessories": "Yes",
        "available": "Yes",
        "productPrice": 799,
        "productStock": 8,
        "productRating": 5.0,
        "selected": false
    },
    {
        "id": 8,
        "imgUrl": "https://i.ibb.co/0GFzTP4/Rectangle-131.png",
        "productTitle": "Cast Watch, Aluminium Case, Starlight Spor",
        "productColor": "Silver",
        "productCategory": "Laptop",
        "accessories": "Yes",
        "available": "Yes",
        "productPrice": 1099,
        "productStock": 11,
        "productRating": 5.0,
        "selected": false
    },
    {
        "id": 9,
        "imgUrl": "https://i.ibb.co/0GFzTP4/Rectangle-131.png",
        "productTitle": "JumpSuit Watch Series , Aluminium Case, Starlight Sport",
        "productColor": "Silver",
        "productCategory": "Laptop",
        "accessories": "Yes",
        "available": "Yes",
        "productPrice": 899,
        "productStock": 14,
        "productRating": 5.0,
        "selected": false
    },
    {
        "id": 10,
        "imgUrl": "https://i.ibb.co/0GFzTP4/Rectangle-131.png",
        "productTitle": "Farcry Surface Pro, Aluminium Case, Starlight Spor",
        "productColor": "Silver",
        "productCategory": "Laptop",
        "accessories": "Yes",
        "available": "Yes",
        "productPrice": 4999,
        "productStock": 19,
        "productRating": 5.0,
        "selected": false
    },
    {
        "id": 11,
        "imgUrl": "https://i.ibb.co/0GFzTP4/Rectangle-131.png",
        "productTitle": "Luke Mouse 2, Aluminium Case, Starlight Spor",
        "productColor": "Silver",
        "productCategory": "Laptop",
        "accessories": "Yes",
        "available": "Yes",
        "productPrice": 8999,
        "productStock": 32,
        "productRating": 5.0,
        "selected": false
    },
    {
        "id": 12,
        "imgUrl": "https://i.ibb.co/0GFzTP4/Rectangle-131.png",
        "productTitle": "Zendesk Watch, Aluminium Case, Starlight Spor",
        "productColor": "Silver",
        "productCategory": "Laptop",
        "accessories": "Yes",
        "available": "Yes",
        "productPrice": 2999,
        "productStock": 1,
        "productRating": 5.0,
        "selected": false
    }
]